-- 코드를 입력하세요
WITH RECURSIVE TIME AS(
    SELECT 0 AS H UNION ALL SELECT H+1 FROM TIME WHERE H < 23)
SELECT H AS 'HOUR', COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM TIME 
LEFT JOIN ANIMAL_OUTS 
ON (H=HOUR(DATETIME))
GROUP BY H;
