SELECT i_i.ITEM_ID, i_i.ITEM_NAME, i_i.RARITY
FROM ITEM_INFO AS i_i
JOIN ITEM_TREE AS it ON it.ITEM_ID = i_i.ITEM_ID
JOIN ITEM_INFO AS ii ON ii.ITEM_ID = it.PARENT_ITEM_ID
WHERE ii.RARITY = 'RARE'
ORDER BY i_i.ITEM_ID DESC;
